// remark-icon.js
import { visit } from 'unist-util-visit';
import { experimental_AstroContainer } from "astro/container"

// @ts-ignore virtual module
import icons from "astro-icon";
// @ts-ignore generated by typegen
import { getIconData, iconToSVG } from '@iconify/utils';

function Icon(name) {
  const setName = "fluent-emoji-flat"
  if(!(name in icons[setName].icons)) {
    console.error("Icon not found: " + name)
    return "<div>icon not Found</div>"
  }

  const collection = icons[setName]

  if (!collection) {
    console.error("Icon collection not found: " + setName)
    return "<div>icon collection not Found</div>"
  }

  const iconData = getIconData(collection, name)

  if (!iconData) {
    console.error("Icon not found: " + name)
    return "<div>icon not Found</div>"
  }

  const id = `ai:${collection.prefix}:${name}`;
  const renderData = iconToSVG(iconData)
  const normalizedProps = { ...renderData.attributes, ...{ width: 24, height: 24} };

  const normalizedBody = renderData.body;
  const { viewBox } = normalizedProps;

  const propsString = Object.entries(normalizedProps)
  .map(([key, value]) => `${key}="${value}"`)
  .join(' ');

  return `<svg ${propsString} data-icon="${name}">
    ${normalizedBody}
  </svg>`;
}

export default function() {
  return async (tree) => {
    visit(tree, 'text', (node, index, parent) => {
      const ICON_SYNTAX = /:([A-Za-z0-9_-]+):/g;  // pattern :iconName:
      let match; 
      let lastIndex = 0;
      const newNodes = [];
      // Find all :name: matches in this text node
      while ((match = ICON_SYNTAX.exec(node.value)) !== null) {
        const iconName = match[1];              // e.g. "name"
        const start = match.index;
        const end = start + match[0].length;
        // Preserve text before the `:name:` 
        if (start > lastIndex) {
          newNodes.push(({
            type: 'text',
            value: node.value.slice(lastIndex, start)
          }));
        }
        // Replace `:name:` with an HTML snippet for the icon
        newNodes.push({
          type: 'html',
          value: Icon(iconName)
        })
          lastIndex = end;
      }
      if (!newNodes.length) return; // no icon syntax found in this node
      // Preserve any trailing text after the last match
      if (lastIndex < node.value.length) {
        newNodes.push({
          type: 'text',
          value: node.value.slice(lastIndex)
        });
      }
      // Replace the original text node with our new nodes
      parent.children.splice(index, 1, ...newNodes);
      return index + newNodes.length; // skip over inserted nodes
    });
  };
}
